# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a631d72f7d221deaad02818ddeb14e02ad516aabdb80fac7b31e4d0eb138174ad5a82fb9c478dc367b85156b5b1e609204900c34f455e2b01095f5eb28e0f71

test:
  secret_key_base: ba51edc84ed67cbeba7dd058651215dd0c54e32a3841e0d365df65bc79584ffed03f13f1eaa485729edc846b47e399c985965ac7e79167dd6f164d4dcc29db83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
